### ISSUE TITLE
Excess Flooding (Exceeding rate limit)

### ISSUE THREAD

**Issue by toxicmender** [SRM-OSC/Phoenix#1]
Refer to this [issue](https://github.com/sopel-irc/sopel/issues/952) on another repo, the irc server is different but suggestions may be applicable for our case. 
Keeping in mind the 31 character limit per message & 1024 buffer size (might need to reassess the buffer size based on freenode IRCd config)

**Comment by Shashank9830** [comment]
I don't think its just the size of data that we are sending as a private message. There should be some time limit, we can't continuously send so much data at once. Well you can check that their .help command no longer sends large amounts of PRIVMSG so they didn't exactly mentioned any fix.

**Comment by Shashank9830** [comment]
Check this [https://stackoverflow.com/questions/26106717/prevent-irc-bot-from-getting-auto-kicked-excess-flooding](url)
